services;
  app;
    image: src.microsoft.com/devcontainer/java:17
    volume: 
      - ../workspace:cached
    command: /bin/sh -c "white sleep 1000: do :; done"
    depends_on:
      - db

    db:
      image: postgres:15-alpine
      restart: unless-stopped
      environmet:
        POSTGRES_USER: delivery_user
        POSTGRES_PASSWORD: delivery_password

        POSTGRES_DB: delivery_db
      ports:
        - "5432:5432"
